#!/usr/bin/env python3
from pylib import *
close("all")

#inputs
argv=sys.argv
if len(argv)==1:
   note='usage: gp hgrid.gr3 "fmt=0; ec=None; fc=None; lw=0.1; levels=None; ticks=None;\n' +\
        '                     xlim=None; ylim=None; clim=None; extend=\'both\'; cb=True;\n' +\
        '                     xticks=None; yticks=None; figsize=[8,6]"\n'
   sys.exit(note+'Note: plot settings are optional')

#open ipython
if argv[1]!='--argument': 
   opts=argv[2] if len(argv)==3 else ''
   os.system('ipython -i {} -- --argument "{}" --argument "{}"'.format(argv[0],argv[1],opts)) 
   sys.exit()

grd=argv[2]; opts=argv[4]
#read grid
gd=loadz(grd).hgrid if grd.endswith('.npz') else read_schism_hgrid(grd)

#get plot options
fmt=0; ec=None; fc=None; lw=0.1; levels=None; ticks=None; xlim=None; ylim=None; clim=None; extend='both'; cb=True
xticks=None; yticks=None; figsize=[8,6]
exec(opts)

#plot
hf=figure(figsize=figsize)
gd.plot(fmt=fmt,ec=ec,fc=fc,lw=lw,levels=levels,ticks=ticks,xlim=xlim,ylim=ylim,clim=clim,extend=extend,cb=cb)
if xticks is not None: setp(gca(),xticks=xticks)
if yticks is not None: setp(gca(),yticks=yticks)
gcf().tight_layout()
show(block=False)
