#!/usr/bin/env python3
import sys, os
from matplotlib.pyplot import figure,show,imshow,imread,axis,gcf,subplots_adjust

if len(sys.argv)==1:
   sys.exit('Usage: pplot *.pp\n')
#hfs=[pickle.load(open(i,'rb')) for i in sys.argv[1:]]; show()

for fname in sys.argv[1:]:
    if fname.endswith('.pp'):
       try:
           from pylib import *
           pplot(fname)
           #hf=read(fname).hf
       except:
           pass
           #import pickle
           #from matplotlib.pyplot import show
           #hf=pickle.load(open(fname,'rb'))
    else:
       data=imread(fname); h,w=data.shape[:2] 
       figure(figsize=[w/115,h/115])
       imshow(data)
       axis('off'); subplots_adjust(top=0.999,bottom=0.001,left=0.001,right=0.999)
       gcf().canvas.manager.set_window_title(fname)

       #old method
       #from PIL import Image
       #hf=Image.open(fname); hf.show()
show()
