#!/usr/bin/env python3
import sys
from PIL import Image

if len(sys.argv)==1:
   sys.exit('Usage: pplot *.pp\n')
#hfs=[pickle.load(open(i,'rb')) for i in sys.argv[1:]]; show()

for fname in sys.argv[1:]:
    if fname.endswith('.pp'):
       try:
           from pylib import *
           pplot(fname)
           #hf=read(fname).hf
       except:
           pass
           #import pickle
           #from matplotlib.pyplot import show
           #hf=pickle.load(open(fname,'rb'))
    else:
       hf=Image.open(fname); hf.show()
show()
