#!/usr/bin/env python3
from pylib import *
close("all")

#inputs
args=sys.argv[1:]; nv=len(args)

#help
if (nv==1 and args[0]=='-h') or nv==0 or nv>2: 
    sys.exit('usage: 1). sms2grd hgrid.2dm\n       2). sms2grd hgrid.2dm new.gr3\n')

#fnames
if nv==1: sms=args[0]; grd=(sms[:-4] if sms.endswith('.2dm') else sms)+'.gr3'
if nv==2: sms,grd=args

sms2grd(sms,grd)
