#!/usr/bin/env python3
import os,time

#inputs
sdir='/home/g/g260135/work/wangzg/DSP/RUN08a/outputs' #source dir.
tdir='/sciclone/pscr/wangzg/DSP/RUN08a/outputs' #target dir. in sciclone

cluster=os.getenv('Hurricane')  #target server
walltime=48 #hours, program exits when runtime exceeds walltime
stime=60    #sleep interval for each loop checking the outputs

#copyfile
snames=[]; stimes=[]; t0=time.time()
while True: 
   #files to be transfered 
   fnames=[i for i in os.listdir(sdir) if((not i.startswith('hotstart_0')) and i.endswith('.nc'))]
   mtimes=[os.path.getmtime(i) for i in fnames]

   iflag=0
   for fname,mtime in zip(fnames,mtimes):
       #check file mtime, and transfer file if it is new
       print(sdir+"/"+fname)
       if (fname in snames) and stimes[snames.index(fname)]>=mtime: continue
       os.system('rsync -raP {}/{} {}{}/'.format(sdir,fname,cluster,tdir)); iflag=0

       #save files transfered
       if fname in snames:
          stimes[snames.index(fname)]=mtime
       else:
          snames.append(fname); stimes.append(mtime)

   #exit the loop
   dt=time.time()-t0
   if (dt/3600>walltime) or iflag>5: sys.exit()
   time.sleep(60)
