#!/usr/bin/env python3
from pylib import *
close("all")

#inputs
args=sys.argv[1:]; nv=len(args)

#help info.
if nv==1 and args[0]=='-h':
   sys.exit('usage: 1). cmb_hotstart (last outputs); 2). cmb_hotstart all')

#check input
fmt=1 if (nv==1 and args[0]=='all') else 0

#combine hotstart
try: 
   combine_schism_hotstart(fmt=fmt)
except:
   combine_schism_hotstart('outputs',fmt=fmt)

