#!/usr/bin/env python3
from pylib import *
close("all")

#inputs
args=sys.argv[1:]; nv=len(args)

#help
if (nv==1 and args[0]=='-h') or nv==0 or nv>2: 
    sys.exit('usage: 1). grd2sms hgrid.gr3\n       2). grd2sms hgrid.gr3 new.2dm\n')

#fnames
if nv==1: grd=args[0]; sms=(grd[:-4] if grd.endswith('.gr3') else grd)+'.2dm'
if nv==2: grd,sms=args

grd2sms(grd,sms)
