#!/usr/bin/env python3
#this script is used to create a python template

import os,sys

#get input
args=sys.argv
if len(args)!=2: sys.exit('\n   usage: pvi fname.py \n')
fname=args[1]

#creat a python script, adding header 
if not os.path.exists(fname):
   fid=open(fname,'w+');
   fid.write('#!/usr/bin/env python3\nfrom pylib import *\nclose("all")\n')
   fid.close()

#open python scripts
os.system('chmod a+x {}; vim {}'.format(fname,fname))
